name: Build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Download Native Binary
        run: |
          mkdir -p ./app/src/main/jniLibs/arm64-v8a
          mkdir -p ./app/src/main/jniLibs/x86_64
          curl -L https://github.com/Exclude0122/libxivpn/releases/latest/download/libxivpn_arm64.so > ./app/src/main/jniLibs/arm64-v8a/libxivpn.so
          curl -L https://github.com/Exclude0122/libxivpn/releases/latest/download/libxivpn_x86_64.so > ./app/src/main/jniLibs/x86_64/libxivpn.so
          sha256sum ./app/src/main/jniLibs/arm64-v8a/libxivpn.so
          sha256sum ./app/src/main/jniLibs/x86_64/libxivpn.so

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
        run: |
          mkdir ./sign
          echo $ENCODED_STRING > sign/keystore-b64.txt
          base64 -d ./sign/keystore-b64.txt > sign/keystore.jks

      - name: Build APK
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Calculate sha256
        run: |
          sha256sum ./app/build/outputs/apk/arm64_v8a/release/app-arm64_v8a-release.apk > sha256.txt
          sha256sum ./app/build/outputs/apk/universal/release/app-universal-release.apk > sha256.txt
          sha256sum ./app/build/outputs/apk/x86_64/release/app-x86_64-release.apk > sha256.txt

      - name: Upload Universal APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release.apk
          path: ./app/build/outputs/apk/universal/release/app-universal-release.apk

      - name: Upload x86_64 APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release.apk
          path: ./app/build/outputs/apk/x86_64/release/app-x86_64-release.apk

      - name: Upload arm64_v8a APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release.apk
          path: ./app/build/outputs/apk/arm64_v8a/release/app-arm64_v8a-release.apk

      - name: Upload SHA256 to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sha256.txt
          path: sha256.txt
